### ISSUE TITLE
get on a resource doesn't populate all fields

### ISSUE THREAD

**Issue by damomurf** [govdelivery/infoblox#33]
Invoking .get on a resource that has been "instantiated" by it's _ref doesn't then populate all of the fields on that resource, for example:

```ruby
host = Infoblox::Host.new(connection: conn, _ref: my_ref)
host.get
puts host.inspect
```
only gives you:

```
#<Infoblox::Host:0x007fa1943d7e70 @connection=#<Infoblox::Connection:70165976540980 @host="https://infoblox.corp.com">, @_ref="record:host/ZG5zLmhvc3QkLjEuY29tLmJsYWNrYm9hcmQuY2F0LWNvbmR1Y3Rvci10ZXN0LWhvc3Q:myhostname.exampke.com/my_view">
```

I would have expected to see name, ipv4addrs, etc, etc.

I have a need to store the _ref's in an external state tracking system and it would be preferable to retrieve existing records by their _ref rather than having to use find which could lead to duplicate or orphaned records in either system?

**Comment by unclebilly** [comment]
@damomurf I'm surprised I half-assed this.  Oh well - it didn't take long to implement.  I pushed out this feature to Rubygems as infoblox-0.5.0.   Cheers! :beers:

**Comment by unclebilly** [comment]
I made it so you can do a one-liner: 

```ruby
host = Infoblox::Host.new(connection: conn, _ref: my_ref).get
```

**Comment by damomurf** [comment]
Awesome! Thanks @unclebilly - and thanks all 'round for the library.

**Comment by unclebilly** [comment]
Yeah - let me know if that doesn't work for you!
