### ISSUE TITLE
Unknown argument/field: 'ipv6addr'

### ISSUE THREAD

**Issue by Carles-Figuerola** [govdelivery/infoblox#35]
When doing a ptr find request, infoblox seems to think that ipv6addr is not a proper return field. Doing a plain GET request from a browser and searching by ipv6addr (https://infoblox.domain.com/wapi/v2.2/record:ptr?ipv6addr) returns "Invalid value" but doing any find request with this gem returns an invalid field. 

```
irb(main):004:0> Infoblox::Ptr.find(connection, {ipv4addr: "10.228.88.114"}).first
{:_return_fields=>"comment,disable,ipv4addr,ipv6addr,name,ptrdname,extensible_attributes,view,zone", :ipv4addr=>"10.228.88.114"}
Infoblox::Error: Error: 400 { "Error": "AdmConProtoError: Unknown argument/field: 'ipv6addr'",
  "code": "Client.Ibap.Proto",
  "text": "Unknown argument/field: 'ipv6addr'"
}
        from /var/lib/gems/1.9.1/gems/infoblox-0.5.0/lib/infoblox/connection.rb:92:in `block in wrap'
        from /var/lib/gems/1.9.1/gems/infoblox-0.5.0/lib/infoblox/connection.rb:90:in `tap'
        from /var/lib/gems/1.9.1/gems/infoblox-0.5.0/lib/infoblox/connection.rb:90:in `wrap'
        from /var/lib/gems/1.9.1/gems/infoblox-0.5.0/lib/infoblox/connection.rb:16:in `get'
        from /var/lib/gems/1.9.1/gems/infoblox-0.5.0/lib/infoblox/resource.rb:110:in `find'
        from (irb):4
        from /usr/bin/irb:12:in `<main>'
```

When changing the resource/ptr.rb to not request ipv6addr the problem doesn't occur and the request returns properly.

Infoblox documentation states that this field does indeed exist

**edit:** Putting more debugging output, I see that I'm using version 1.0 of the api with this gem (hadn't found how to change the version on demand until I read the lib/infoblox.rb source). The point of this issue would be that this gem is requesting ipv6addr in ptr requests for api levels under 1.2 which is not supported as per the documentation.

**Comment by unclebilly** [comment]
I would entertain a pull request with conditional addition of the `ipv6addr` field (based on the value of `Infoblox.wapi_version`).  This is already done elsewhere in the gem.  

Do you happen to know if IPv6 was added to the whole system in version 1.2, or if it was just the `Ptr` resource that got it?

**Comment by Carles-Figuerola** [comment]
I found out that the version that first supported this field is 1.1 instead of 1.2 and I only found the resource Host to have something similar in the same version (ipv6addrs). Added a conditional attribute for both
