### ISSUE TITLE
Ptr class should have :ttl as an attribute

### ISSUE THREAD

**Issue by jerryu** [govdelivery/infoblox#38]
When I use this gem to reduce TTL for both A & PTR records in preparation for a pending change, I was surprised that :ttl is not listed as an attribute for Ptr class.

Since Infoblox is new to me, I am not sure whether this omission is by design. For my purpose, I added :ttl as a new attribute for Ptr class in my local clone and it worked fine.

I'll be more than happy to submit a pull request, if this omission was not by design.

**Comment by unclebilly** [comment]
The omission was not by design - I've only implemented the attributes that have been useful for me (and other people) thus far.  As you can see, it's fairly straightforward to add new ones.  I'd be happy to accept a pull request!
