### ISSUE TITLE
Resource for restarting services

### ISSUE THREAD

**Issue by zachsmorgan** [govdelivery/infoblox#40]
The WAPI forum post (https://community.infoblox.com/t5/API-Integration/The-definitive-list-of-REST-examples/td-p/1214) details posting to the grid ref with something like 
?_function=restartservices&member_order=SEQUENTIALLY...

Is there a grid resource that I'm overlooking or is this feature not present in this gem?

**Comment by unclebilly** [comment]
Hi @zachsmorgan - You're correct in that the feature is not present.  It looks like there is a fork or two with this feature - I'd be happy to accept a pull request with good tests.
