### ISSUE TITLE
SSL verification is hard-coded to false

### ISSUE THREAD

**Issue by synthead** [govdelivery/infoblox#44]
In [line 54 of `connection.rb`](https://github.com/govdelivery/infoblox/blob/c9839d8a30d7ff24bf45c3ccb00a2ca8da10625f/lib/infoblox/connection.rb#L54), SSL verification is permanently disabled:
```ruby
    def connection
      @connection ||= Faraday.new(:url => self.host, :ssl => {:verify => false}) do |faraday|
        faraday.use Faraday::Response::Logger, logger if logger
        faraday.request :json
        faraday.basic_auth(self.username, self.password)
        faraday.adapter(self.adapter, &self.adapter_block)
      end
    end
```

SSL should be verified unless the user explicitly disables it.  There's [an `ssl_opts` variable that's set during initialization](https://github.com/govdelivery/infoblox/blob/c9839d8a30d7ff24bf45c3ccb00a2ca8da10625f/lib/infoblox/connection.rb#L50), but it appears to never be used anywhere in this gem.  This would be a good place to store the user's SSL verification setting to later be read in the `connection` method.

**Comment by unclebilly** [comment]
Thanks for submitting the issue.  I fixed it and added an example in the readme demonstrating how to use the ssl options.  Look for another release in a bit.  It's going to have to be a major release, as this will definitely break some folks' integrations.
