### ISSUE TITLE
Infoblox::Connection.new broken?

### ISSUE THREAD

**Issue by iamthemuffinman** [govdelivery/infoblox#48]
I'm having an issue where I try to list all networks and I get a 401. Here's a basic version:
```rb
connection = Infoblox::Connection.new(host: 'https://myhost.local', username: 'nope', password: 'nope', ssl_opts: {verify: false})
# this seems wrong, shouldn't the username and password be in here?
=> <Infoblox::Connection:70103408887440 @host="https://myhost.local">

network = Infoblox::Network.all(connection)
```

If I do that, I get:
```
content-length: "401"
content-type: "text/html; charset=iso-8859-1"
connection: "close"
Infoblox::Error: Error: 401 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

The part that seems off to me is that the connection object only returns the host, shouldn't it have the username and password as well?

**Comment by teaforthecat** [comment]
That is what you would normally expect but the `inspect` method is being defined/overridden.
```ruby
    ##
    # Don't display the username/password in logging, etc. 
    #
    def inspect
      "#<#{self.class}:#{object_id} @host=\"#{@host}\">"
    end
```
You should be able to puts the attributes individually though.
All I can think of is, do you need a domain in the username? Let us know how this works out

**Comment by iamthemuffinman** [comment]
@teaforthecat That was quick. Ah, I see. Okay, that makes sense.

Hmm. I don't need a domain when I log in to the web UI. Should they be the same?

**Comment by teaforthecat** [comment]
Yes they should. Could it be a permissions issue? I'm looking at this: https://community.infoblox.com/t5/Security/API-Permissions/td-p/1039

**Comment by iamthemuffinman** [comment]
I'll bet that's probably what it is. I didn't know the API was under a different permission set. I'll go ahead and close this. Thanks for the help @teaforthecat!
