### ISSUE TITLE
Rails 5.1 compatibility

### ISSUE THREAD

**Issue by clarkent86** [govdelivery/infoblox#55]
lib/infoblox/resource.rb line 110

connection.get(resource_uri, params) returns:

*** Faraday::SSLError Exception: SSL_connect returned=1 errno=0 state=error: certificate verify failed

with Rails 5.1 where previously this gem worked fine on Rails 5.0.1 . I'm still digging into whether or not it's actually a cert SSL issue on our end but nothing seems to be working with valid certs.

I'll also submit this to an issue on Rails since I'm not exactly sure where/why this is failing.

**Comment by unclebilly** [comment]
Looks like your SSL certificate is invalid.  This is not an issue with the Infoblox gem - but the behavior for validation changed between Infoblox gem versions 0.5.3 and 1.0.0.  You can use the `ssl_opts` hash to disable certificate validation to test your code, but I recommend that you don't disable validation for production code.  See the README for how to use `ssl_opts`.

**Comment by clarkent86** [comment]
Yup, it was the difference between gem versions and how it handles cert validation. I'll see if I can find out how to use the new functionality. Thanks!

**Comment by clarkent86** [comment]
@unclebilly Does this gem require the CN to be SAN?

**Comment by unclebilly** [comment]
This gem uses the [Faraday](https://github.com/lostisland/faraday) gem for network stuff.  Faraday by default uses [Net::HTTP](http://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html) (from the Ruby stdlib) to make HTTP requests to your Infoblox instance.  Net::HTTP in turn uses [OpenSSL](http://ruby-doc.org/stdlib-2.4.1/libdoc/openssl/rdoc/OpenSSL.html) to negotiate secure connections - also part of the Ruby stdlib.  I don't know much about SSL, but I do know that this gem (Infoblox) does nothing but pass your options to Farday, which in turn end up getting passed on to OpenSSL somehow.
