### ISSUE TITLE
Fixedaddress name

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [govdelivery/infoblox#56]
Hey, I would've just submitted a PR for this but I'm not sure if I should fix the README or the classname

In the readme, the class for a fixed address is ```FixedAddress``` however the class name is actually ```Fixedaddress``` 

From this repo's history it looks like that has always been the case, but every other class name is CamelCase.

**Comment by unclebilly** [comment]
I created PR #57 for this.  Thanks for your feedback!
